// Common emojis with keywords for quick search
export const EMOJI_LIST: { emoji: string; keywords: string[] }[] = [
  // Faces - happy
  { emoji: '😀', keywords: ['grinning', 'happy', 'smile'] },
  { emoji: '😃', keywords: ['smiley', 'happy', 'smile'] },
  { emoji: '😄', keywords: ['smile', 'happy', 'joy'] },
  { emoji: '😁', keywords: ['grin', 'happy', 'beam'] },
  { emoji: '😆', keywords: ['laughing', 'satisfied', 'lol'] },
  { emoji: '😅', keywords: ['sweat', 'nervous', 'relief'] },
  { emoji: '🤣', keywords: ['rofl', 'laughing', 'lol'] },
  { emoji: '😂', keywords: ['joy', 'tears', 'laughing', 'lol', 'crying'] },
  { emoji: '🙂', keywords: ['slightly', 'smile'] },
  { emoji: '😊', keywords: ['blush', 'smile', 'happy'] },
  { emoji: '😇', keywords: ['innocent', 'angel', 'halo'] },

  // Faces - love
  { emoji: '🥰', keywords: ['love', 'hearts', 'adore'] },
  { emoji: '😍', keywords: ['heart', 'eyes', 'love'] },
  { emoji: '🤩', keywords: ['star', 'struck', 'excited'] },
  { emoji: '😘', keywords: ['kiss', 'love', 'blow'] },
  { emoji: '😗', keywords: ['kiss', 'smooch'] },
  { emoji: '😚', keywords: ['kiss', 'blush'] },
  { emoji: '😙', keywords: ['kiss', 'smile'] },

  // Faces - playful
  { emoji: '😋', keywords: ['yum', 'delicious', 'tasty', 'food'] },
  { emoji: '😛', keywords: ['tongue', 'playful'] },
  { emoji: '😜', keywords: ['wink', 'tongue', 'crazy'] },
  { emoji: '🤪', keywords: ['zany', 'crazy', 'wild'] },
  { emoji: '😝', keywords: ['tongue', 'squint'] },
  { emoji: '🤑', keywords: ['money', 'rich', 'dollar'] },

  // Faces - cool/thinking
  { emoji: '🤗', keywords: ['hug', 'hugging', 'embrace'] },
  { emoji: '🤭', keywords: ['giggle', 'oops', 'cover'] },
  { emoji: '🤫', keywords: ['shush', 'quiet', 'secret'] },
  { emoji: '🤔', keywords: ['thinking', 'think', 'hmm'] },
  { emoji: '🤐', keywords: ['zipper', 'quiet', 'secret'] },
  { emoji: '🤨', keywords: ['raised', 'eyebrow', 'skeptical'] },
  { emoji: '😐', keywords: ['neutral', 'meh'] },
  { emoji: '😑', keywords: ['expressionless', 'blank'] },
  { emoji: '😶', keywords: ['silent', 'speechless', 'mute'] },
  { emoji: '😏', keywords: ['smirk', 'smug'] },
  { emoji: '😒', keywords: ['unamused', 'meh', 'bored'] },
  { emoji: '🙄', keywords: ['eyeroll', 'rolling', 'whatever'] },
  { emoji: '😬', keywords: ['grimace', 'awkward', 'nervous'] },
  { emoji: '🤥', keywords: ['lying', 'pinocchio', 'lie'] },
  { emoji: '😌', keywords: ['relieved', 'peaceful', 'calm'] },
  { emoji: '😔', keywords: ['pensive', 'sad', 'thoughtful'] },
  { emoji: '😪', keywords: ['sleepy', 'tired'] },
  { emoji: '🤤', keywords: ['drool', 'hungry', 'want'] },
  { emoji: '😴', keywords: ['sleep', 'zzz', 'tired'] },
  { emoji: '🥱', keywords: ['yawn', 'tired', 'bored'] },

  // Faces - unwell
  { emoji: '😷', keywords: ['mask', 'sick', 'covid'] },
  { emoji: '🤒', keywords: ['sick', 'fever', 'ill'] },
  { emoji: '🤕', keywords: ['hurt', 'bandage', 'injured'] },
  { emoji: '🤢', keywords: ['nausea', 'sick', 'gross'] },
  { emoji: '🤮', keywords: ['vomit', 'sick', 'puke'] },
  { emoji: '🤧', keywords: ['sneeze', 'sick', 'cold'] },
  { emoji: '🥵', keywords: ['hot', 'heat', 'sweating'] },
  { emoji: '🥶', keywords: ['cold', 'freezing', 'frozen'] },
  { emoji: '🥴', keywords: ['woozy', 'drunk', 'dizzy'] },
  { emoji: '😵', keywords: ['dizzy', 'dead', 'knocked'] },
  { emoji: '🤯', keywords: ['mindblown', 'exploding', 'shocked'] },

  // Faces - sad/concerned
  { emoji: '😕', keywords: ['confused', 'puzzled'] },
  { emoji: '😟', keywords: ['worried', 'concerned'] },
  { emoji: '🙁', keywords: ['frown', 'sad'] },
  { emoji: '☹️', keywords: ['frown', 'sad', 'unhappy'] },
  { emoji: '😮', keywords: ['open', 'surprised', 'wow'] },
  { emoji: '😯', keywords: ['hushed', 'surprised'] },
  { emoji: '😲', keywords: ['astonished', 'shocked', 'wow'] },
  { emoji: '😳', keywords: ['flushed', 'embarrassed', 'shy'] },
  { emoji: '🥺', keywords: ['pleading', 'puppy', 'please', 'cute'] },
  { emoji: '😦', keywords: ['frown', 'surprised'] },
  { emoji: '😧', keywords: ['anguished', 'worried'] },
  { emoji: '😨', keywords: ['fearful', 'scared'] },
  { emoji: '😰', keywords: ['anxious', 'sweat', 'nervous'] },
  { emoji: '😥', keywords: ['sad', 'relieved', 'disappointed'] },
  { emoji: '😢', keywords: ['cry', 'sad', 'tear'] },
  { emoji: '😭', keywords: ['sob', 'crying', 'sad', 'tears'] },
  { emoji: '😱', keywords: ['scream', 'fear', 'horror', 'scared'] },
  { emoji: '😖', keywords: ['confounded', 'frustrated'] },
  { emoji: '😣', keywords: ['persevere', 'struggle'] },
  { emoji: '😞', keywords: ['disappointed', 'sad'] },
  { emoji: '😓', keywords: ['downcast', 'sweat', 'sad'] },
  { emoji: '😩', keywords: ['weary', 'tired', 'exhausted'] },
  { emoji: '😫', keywords: ['tired', 'exhausted'] },

  // Faces - angry
  { emoji: '🥱', keywords: ['yawn', 'tired', 'sleepy'] },
  { emoji: '😤', keywords: ['triumph', 'steam', 'angry'] },
  { emoji: '😡', keywords: ['angry', 'mad', 'rage'] },
  { emoji: '😠', keywords: ['angry', 'mad'] },
  { emoji: '🤬', keywords: ['cursing', 'swear', 'angry'] },

  // Faces - costume
  { emoji: '😈', keywords: ['devil', 'evil', 'horns'] },
  { emoji: '👿', keywords: ['devil', 'angry', 'imp'] },
  { emoji: '💀', keywords: ['skull', 'dead', 'death'] },
  { emoji: '☠️', keywords: ['skull', 'crossbones', 'danger'] },
  { emoji: '💩', keywords: ['poop', 'poo', 'shit'] },
  { emoji: '🤡', keywords: ['clown', 'circus'] },
  { emoji: '👹', keywords: ['ogre', 'monster'] },
  { emoji: '👺', keywords: ['goblin', 'tengu'] },
  { emoji: '👻', keywords: ['ghost', 'boo', 'spooky'] },
  { emoji: '👽', keywords: ['alien', 'ufo', 'et'] },
  { emoji: '👾', keywords: ['alien', 'monster', 'game'] },
  { emoji: '🤖', keywords: ['robot', 'bot'] },

  // Cats
  { emoji: '😺', keywords: ['cat', 'smile', 'happy'] },
  { emoji: '😸', keywords: ['cat', 'grin'] },
  { emoji: '😹', keywords: ['cat', 'joy', 'tears'] },
  { emoji: '😻', keywords: ['cat', 'heart', 'love'] },
  { emoji: '😼', keywords: ['cat', 'smirk'] },
  { emoji: '😽', keywords: ['cat', 'kiss'] },
  { emoji: '🙀', keywords: ['cat', 'weary', 'shocked'] },
  { emoji: '😿', keywords: ['cat', 'cry', 'sad'] },
  { emoji: '😾', keywords: ['cat', 'pout', 'angry'] },

  // Gestures
  { emoji: '👋', keywords: ['wave', 'hi', 'hello', 'bye'] },
  { emoji: '🤚', keywords: ['hand', 'raised', 'stop'] },
  { emoji: '🖐️', keywords: ['hand', 'fingers', 'five'] },
  { emoji: '✋', keywords: ['hand', 'stop', 'high five'] },
  { emoji: '🖖', keywords: ['vulcan', 'spock', 'star trek'] },
  { emoji: '👌', keywords: ['ok', 'okay', 'perfect'] },
  { emoji: '🤌', keywords: ['pinch', 'italian', 'chef'] },
  { emoji: '🤏', keywords: ['pinch', 'small', 'little'] },
  { emoji: '✌️', keywords: ['peace', 'victory', 'v'] },
  { emoji: '🤞', keywords: ['crossed', 'fingers', 'luck'] },
  { emoji: '🤟', keywords: ['love', 'rock', 'horns'] },
  { emoji: '🤘', keywords: ['rock', 'metal', 'horns'] },
  { emoji: '🤙', keywords: ['call', 'shaka', 'hang loose'] },
  { emoji: '👈', keywords: ['point', 'left'] },
  { emoji: '👉', keywords: ['point', 'right'] },
  { emoji: '👆', keywords: ['point', 'up'] },
  { emoji: '👇', keywords: ['point', 'down'] },
  { emoji: '☝️', keywords: ['point', 'up', 'one'] },
  { emoji: '👍', keywords: ['thumbs', 'up', 'yes', 'like', 'good'] },
  { emoji: '👎', keywords: ['thumbs', 'down', 'no', 'dislike', 'bad'] },
  { emoji: '✊', keywords: ['fist', 'punch', 'power'] },
  { emoji: '👊', keywords: ['fist', 'bump', 'punch'] },
  { emoji: '🤛', keywords: ['fist', 'left'] },
  { emoji: '🤜', keywords: ['fist', 'right'] },
  { emoji: '👏', keywords: ['clap', 'applause', 'bravo'] },
  { emoji: '🙌', keywords: ['raise', 'hands', 'celebration', 'praise'] },
  { emoji: '👐', keywords: ['open', 'hands'] },
  { emoji: '🤲', keywords: ['palms', 'together'] },
  { emoji: '🤝', keywords: ['handshake', 'deal', 'agreement'] },
  { emoji: '🙏', keywords: ['pray', 'please', 'thanks', 'namaste'] },
  { emoji: '✍️', keywords: ['write', 'writing'] },
  { emoji: '💪', keywords: ['muscle', 'strong', 'flex', 'bicep'] },

  // Hearts
  { emoji: '❤️', keywords: ['heart', 'love', 'red'] },
  { emoji: '🧡', keywords: ['heart', 'orange'] },
  { emoji: '💛', keywords: ['heart', 'yellow'] },
  { emoji: '💚', keywords: ['heart', 'green'] },
  { emoji: '💙', keywords: ['heart', 'blue'] },
  { emoji: '💜', keywords: ['heart', 'purple'] },
  { emoji: '🖤', keywords: ['heart', 'black'] },
  { emoji: '🤍', keywords: ['heart', 'white'] },
  { emoji: '🤎', keywords: ['heart', 'brown'] },
  { emoji: '💔', keywords: ['heart', 'broken', 'sad'] },
  { emoji: '❣️', keywords: ['heart', 'exclamation'] },
  { emoji: '💕', keywords: ['hearts', 'two', 'love'] },
  { emoji: '💞', keywords: ['hearts', 'revolving'] },
  { emoji: '💓', keywords: ['heart', 'beating'] },
  { emoji: '💗', keywords: ['heart', 'growing'] },
  { emoji: '💖', keywords: ['heart', 'sparkling'] },
  { emoji: '💘', keywords: ['heart', 'arrow', 'cupid'] },
  { emoji: '💝', keywords: ['heart', 'ribbon', 'gift'] },

  // Food & Drink
  { emoji: '🍕', keywords: ['pizza', 'food'] },
  { emoji: '🍔', keywords: ['burger', 'hamburger', 'food'] },
  { emoji: '🍟', keywords: ['fries', 'food'] },
  { emoji: '🌭', keywords: ['hotdog', 'food'] },
  { emoji: '🍿', keywords: ['popcorn', 'movie', 'snack'] },
  { emoji: '🧂', keywords: ['salt', 'salty'] },
  { emoji: '🥓', keywords: ['bacon', 'food'] },
  { emoji: '🥚', keywords: ['egg', 'food'] },
  { emoji: '🍳', keywords: ['egg', 'cooking', 'breakfast'] },
  { emoji: '🥞', keywords: ['pancakes', 'breakfast'] },
  { emoji: '🧇', keywords: ['waffle', 'breakfast'] },
  { emoji: '🥐', keywords: ['croissant', 'bread', 'french'] },
  { emoji: '🍞', keywords: ['bread', 'toast'] },
  { emoji: '🥖', keywords: ['baguette', 'bread', 'french'] },
  { emoji: '🥨', keywords: ['pretzel', 'snack'] },
  { emoji: '🧀', keywords: ['cheese'] },
  { emoji: '🥗', keywords: ['salad', 'healthy', 'food'] },
  { emoji: '🌮', keywords: ['taco', 'mexican', 'food'] },
  { emoji: '🌯', keywords: ['burrito', 'mexican', 'food'] },
  { emoji: '🍜', keywords: ['noodles', 'ramen', 'food'] },
  { emoji: '🍝', keywords: ['pasta', 'spaghetti', 'food'] },
  { emoji: '🍣', keywords: ['sushi', 'japanese', 'food'] },
  { emoji: '🍱', keywords: ['bento', 'japanese', 'food'] },
  { emoji: '🍛', keywords: ['curry', 'indian', 'food'] },
  { emoji: '🍲', keywords: ['stew', 'pot', 'food'] },
  { emoji: '🥘', keywords: ['pan', 'food', 'paella'] },
  { emoji: '🍰', keywords: ['cake', 'dessert', 'sweet'] },
  { emoji: '🎂', keywords: ['birthday', 'cake', 'celebration'] },
  { emoji: '🧁', keywords: ['cupcake', 'dessert', 'sweet'] },
  { emoji: '🍩', keywords: ['donut', 'doughnut', 'sweet'] },
  { emoji: '🍪', keywords: ['cookie', 'sweet', 'snack'] },
  { emoji: '🍫', keywords: ['chocolate', 'sweet'] },
  { emoji: '🍬', keywords: ['candy', 'sweet'] },
  { emoji: '🍭', keywords: ['lollipop', 'candy', 'sweet'] },
  { emoji: '🍦', keywords: ['ice cream', 'dessert', 'sweet'] },
  { emoji: '🍨', keywords: ['ice cream', 'sundae', 'dessert'] },
  { emoji: '☕', keywords: ['coffee', 'drink', 'cafe'] },
  { emoji: '🍵', keywords: ['tea', 'drink', 'green'] },
  { emoji: '🧃', keywords: ['juice', 'box', 'drink'] },
  { emoji: '🥤', keywords: ['soda', 'drink', 'cup'] },
  { emoji: '🧋', keywords: ['boba', 'bubble tea', 'drink'] },
  { emoji: '🍺', keywords: ['beer', 'drink', 'alcohol'] },
  { emoji: '🍻', keywords: ['beers', 'cheers', 'drink'] },
  { emoji: '🥂', keywords: ['champagne', 'cheers', 'toast'] },
  { emoji: '🍷', keywords: ['wine', 'drink', 'alcohol'] },
  { emoji: '🍸', keywords: ['cocktail', 'martini', 'drink'] },
  { emoji: '🍹', keywords: ['tropical', 'drink', 'cocktail'] },

  // Fruits & Vegetables
  { emoji: '🍎', keywords: ['apple', 'red', 'fruit'] },
  { emoji: '🍏', keywords: ['apple', 'green', 'fruit'] },
  { emoji: '🍊', keywords: ['orange', 'tangerine', 'fruit'] },
  { emoji: '🍋', keywords: ['lemon', 'fruit', 'sour'] },
  { emoji: '🍌', keywords: ['banana', 'fruit'] },
  { emoji: '🍉', keywords: ['watermelon', 'fruit', 'summer'] },
  { emoji: '🍇', keywords: ['grapes', 'fruit'] },
  { emoji: '🍓', keywords: ['strawberry', 'fruit', 'berry'] },
  { emoji: '🫐', keywords: ['blueberry', 'fruit', 'berry'] },
  { emoji: '🍒', keywords: ['cherry', 'fruit'] },
  { emoji: '🍑', keywords: ['peach', 'fruit', 'butt'] },
  { emoji: '🥭', keywords: ['mango', 'fruit'] },
  { emoji: '🍍', keywords: ['pineapple', 'fruit'] },
  { emoji: '🥥', keywords: ['coconut', 'fruit'] },
  { emoji: '🥑', keywords: ['avocado', 'fruit', 'guac'] },
  { emoji: '🍆', keywords: ['eggplant', 'aubergine', 'vegetable'] },
  { emoji: '🥒', keywords: ['cucumber', 'vegetable'] },
  { emoji: '🥕', keywords: ['carrot', 'vegetable'] },
  { emoji: '🌽', keywords: ['corn', 'vegetable'] },
  { emoji: '🌶️', keywords: ['pepper', 'hot', 'spicy', 'chili'] },
  { emoji: '🫑', keywords: ['pepper', 'bell', 'vegetable'] },
  { emoji: '🥦', keywords: ['broccoli', 'vegetable'] },
  { emoji: '🧄', keywords: ['garlic', 'vegetable'] },
  { emoji: '🧅', keywords: ['onion', 'vegetable'] },
  { emoji: '🥔', keywords: ['potato', 'vegetable'] },
  { emoji: '🍠', keywords: ['sweet potato', 'vegetable'] },

  // Fire, stars, weather
  { emoji: '🔥', keywords: ['fire', 'hot', 'lit', 'flame'] },
  { emoji: '⭐', keywords: ['star'] },
  { emoji: '🌟', keywords: ['star', 'glowing', 'sparkle'] },
  { emoji: '✨', keywords: ['sparkles', 'magic', 'stars'] },
  { emoji: '💫', keywords: ['dizzy', 'star', 'shooting'] },
  { emoji: '⚡', keywords: ['lightning', 'bolt', 'electric', 'zap'] },
  { emoji: '☀️', keywords: ['sun', 'sunny', 'weather'] },
  { emoji: '🌤️', keywords: ['sun', 'cloud', 'weather'] },
  { emoji: '⛅', keywords: ['cloud', 'sun', 'weather'] },
  { emoji: '🌥️', keywords: ['cloud', 'sun', 'weather'] },
  { emoji: '☁️', keywords: ['cloud', 'weather'] },
  { emoji: '🌦️', keywords: ['rain', 'sun', 'weather'] },
  { emoji: '🌧️', keywords: ['rain', 'weather'] },
  { emoji: '⛈️', keywords: ['storm', 'thunder', 'weather'] },
  { emoji: '🌩️', keywords: ['lightning', 'storm', 'weather'] },
  { emoji: '🌨️', keywords: ['snow', 'weather', 'cold'] },
  { emoji: '❄️', keywords: ['snow', 'cold', 'winter', 'snowflake'] },
  { emoji: '🌪️', keywords: ['tornado', 'weather'] },
  { emoji: '🌈', keywords: ['rainbow', 'weather', 'pride'] },

  // Animals
  { emoji: '🐶', keywords: ['dog', 'puppy', 'pet'] },
  { emoji: '🐱', keywords: ['cat', 'kitten', 'pet'] },
  { emoji: '🐭', keywords: ['mouse', 'animal'] },
  { emoji: '🐹', keywords: ['hamster', 'pet'] },
  { emoji: '🐰', keywords: ['rabbit', 'bunny', 'pet'] },
  { emoji: '🦊', keywords: ['fox', 'animal'] },
  { emoji: '🐻', keywords: ['bear', 'animal'] },
  { emoji: '🐼', keywords: ['panda', 'bear', 'animal'] },
  { emoji: '🐨', keywords: ['koala', 'animal'] },
  { emoji: '🐯', keywords: ['tiger', 'animal'] },
  { emoji: '🦁', keywords: ['lion', 'animal', 'king'] },
  { emoji: '🐮', keywords: ['cow', 'animal'] },
  { emoji: '🐷', keywords: ['pig', 'animal'] },
  { emoji: '🐸', keywords: ['frog', 'animal'] },
  { emoji: '🐵', keywords: ['monkey', 'animal'] },
  { emoji: '🙈', keywords: ['monkey', 'see no evil'] },
  { emoji: '🙉', keywords: ['monkey', 'hear no evil'] },
  { emoji: '🙊', keywords: ['monkey', 'speak no evil'] },
  { emoji: '🐔', keywords: ['chicken', 'bird', 'animal'] },
  { emoji: '🐧', keywords: ['penguin', 'bird', 'animal'] },
  { emoji: '🐦', keywords: ['bird', 'animal'] },
  { emoji: '🦅', keywords: ['eagle', 'bird', 'animal'] },
  { emoji: '🦆', keywords: ['duck', 'bird', 'animal'] },
  { emoji: '🦉', keywords: ['owl', 'bird', 'animal'] },
  { emoji: '🦇', keywords: ['bat', 'animal'] },
  { emoji: '🐺', keywords: ['wolf', 'animal'] },
  { emoji: '🐴', keywords: ['horse', 'animal'] },
  { emoji: '🦄', keywords: ['unicorn', 'animal', 'magic'] },
  { emoji: '🐝', keywords: ['bee', 'insect', 'honey'] },
  { emoji: '🦋', keywords: ['butterfly', 'insect'] },
  { emoji: '🐌', keywords: ['snail', 'slow'] },
  { emoji: '🐛', keywords: ['bug', 'insect'] },
  { emoji: '🐢', keywords: ['turtle', 'slow', 'animal'] },
  { emoji: '🐍', keywords: ['snake', 'animal'] },
  { emoji: '🦎', keywords: ['lizard', 'animal'] },
  { emoji: '🐙', keywords: ['octopus', 'animal', 'sea'] },
  { emoji: '🦑', keywords: ['squid', 'animal', 'sea'] },
  { emoji: '🦐', keywords: ['shrimp', 'animal', 'sea'] },
  { emoji: '🦞', keywords: ['lobster', 'animal', 'sea'] },
  { emoji: '🦀', keywords: ['crab', 'animal', 'sea'] },
  { emoji: '🐠', keywords: ['fish', 'animal', 'sea'] },
  { emoji: '🐟', keywords: ['fish', 'animal', 'sea'] },
  { emoji: '🐬', keywords: ['dolphin', 'animal', 'sea'] },
  { emoji: '🐳', keywords: ['whale', 'animal', 'sea'] },
  { emoji: '🦈', keywords: ['shark', 'animal', 'sea'] },

  // Celebration & Objects
  { emoji: '🎉', keywords: ['party', 'celebration', 'tada', 'congrats'] },
  { emoji: '🎊', keywords: ['confetti', 'party', 'celebration'] },
  { emoji: '🎈', keywords: ['balloon', 'party', 'celebration'] },
  { emoji: '🎁', keywords: ['gift', 'present', 'birthday'] },
  { emoji: '🎀', keywords: ['ribbon', 'bow', 'gift'] },
  { emoji: '🏆', keywords: ['trophy', 'winner', 'award'] },
  { emoji: '🥇', keywords: ['gold', 'medal', 'first', 'winner'] },
  { emoji: '🥈', keywords: ['silver', 'medal', 'second'] },
  { emoji: '🥉', keywords: ['bronze', 'medal', 'third'] },
  { emoji: '⚽', keywords: ['soccer', 'football', 'sport'] },
  { emoji: '🏀', keywords: ['basketball', 'sport'] },
  { emoji: '🏈', keywords: ['football', 'american', 'sport'] },
  { emoji: '⚾', keywords: ['baseball', 'sport'] },
  { emoji: '🎾', keywords: ['tennis', 'sport'] },
  { emoji: '🏐', keywords: ['volleyball', 'sport'] },
  { emoji: '🎱', keywords: ['pool', 'billiards', 'eight ball'] },
  { emoji: '🎯', keywords: ['target', 'bullseye', 'dart'] },
  { emoji: '🎮', keywords: ['game', 'controller', 'video game'] },
  { emoji: '🎲', keywords: ['dice', 'game', 'random'] },
  { emoji: '🎭', keywords: ['theater', 'drama', 'masks'] },
  { emoji: '🎨', keywords: ['art', 'paint', 'palette'] },
  { emoji: '🎬', keywords: ['movie', 'film', 'action'] },
  { emoji: '🎤', keywords: ['mic', 'microphone', 'karaoke', 'sing'] },
  { emoji: '🎧', keywords: ['headphones', 'music', 'audio'] },
  { emoji: '🎵', keywords: ['music', 'note', 'song'] },
  { emoji: '🎶', keywords: ['music', 'notes', 'song'] },
  { emoji: '🎹', keywords: ['piano', 'keyboard', 'music'] },
  { emoji: '🎸', keywords: ['guitar', 'music', 'rock'] },
  { emoji: '🎺', keywords: ['trumpet', 'music'] },
  { emoji: '🎻', keywords: ['violin', 'music'] },
  { emoji: '📱', keywords: ['phone', 'mobile', 'smartphone'] },
  { emoji: '💻', keywords: ['laptop', 'computer'] },
  { emoji: '🖥️', keywords: ['desktop', 'computer', 'monitor'] },
  { emoji: '📷', keywords: ['camera', 'photo'] },
  { emoji: '📸', keywords: ['camera', 'flash', 'photo'] },
  { emoji: '📹', keywords: ['video', 'camera', 'record'] },
  { emoji: '🎥', keywords: ['movie', 'camera', 'film'] },
  { emoji: '📺', keywords: ['tv', 'television'] },
  { emoji: '📻', keywords: ['radio'] },
  { emoji: '⏰', keywords: ['alarm', 'clock', 'time'] },
  { emoji: '⌚', keywords: ['watch', 'time'] },
  { emoji: '💡', keywords: ['lightbulb', 'idea', 'light'] },
  { emoji: '🔦', keywords: ['flashlight', 'torch', 'light'] },
  { emoji: '💰', keywords: ['money', 'bag', 'rich'] },
  { emoji: '💵', keywords: ['money', 'dollar', 'cash'] },
  { emoji: '💸', keywords: ['money', 'flying', 'spend'] },
  { emoji: '💳', keywords: ['card', 'credit', 'payment'] },
  { emoji: '💎', keywords: ['diamond', 'gem', 'jewel'] },
  { emoji: '🔑', keywords: ['key', 'lock'] },
  { emoji: '🔒', keywords: ['lock', 'secure', 'locked'] },
  { emoji: '🔓', keywords: ['unlock', 'unlocked', 'open'] },

  // Symbols & Arrows
  { emoji: '✅', keywords: ['check', 'done', 'yes', 'complete'] },
  { emoji: '❌', keywords: ['x', 'no', 'cross', 'wrong'] },
  { emoji: '❓', keywords: ['question', 'what'] },
  { emoji: '❗', keywords: ['exclamation', 'important', 'alert'] },
  { emoji: '‼️', keywords: ['exclamation', 'double', 'important'] },
  { emoji: '⁉️', keywords: ['exclamation', 'question'] },
  { emoji: '💯', keywords: ['hundred', 'perfect', 'score'] },
  { emoji: '🔴', keywords: ['red', 'circle'] },
  { emoji: '🟠', keywords: ['orange', 'circle'] },
  { emoji: '🟡', keywords: ['yellow', 'circle'] },
  { emoji: '🟢', keywords: ['green', 'circle'] },
  { emoji: '🔵', keywords: ['blue', 'circle'] },
  { emoji: '🟣', keywords: ['purple', 'circle'] },
  { emoji: '⚫', keywords: ['black', 'circle'] },
  { emoji: '⚪', keywords: ['white', 'circle'] },
  { emoji: '🟤', keywords: ['brown', 'circle'] },
  { emoji: '➡️', keywords: ['arrow', 'right'] },
  { emoji: '⬅️', keywords: ['arrow', 'left'] },
  { emoji: '⬆️', keywords: ['arrow', 'up'] },
  { emoji: '⬇️', keywords: ['arrow', 'down'] },
  { emoji: '↩️', keywords: ['arrow', 'return', 'back'] },
  { emoji: '↪️', keywords: ['arrow', 'forward'] },
  { emoji: '🔄', keywords: ['arrows', 'refresh', 'reload', 'repeat'] },
  { emoji: '🔃', keywords: ['arrows', 'clockwise'] },
  { emoji: '🔙', keywords: ['back', 'arrow'] },
  { emoji: '🔚', keywords: ['end', 'arrow'] },
  { emoji: '🔛', keywords: ['on', 'arrow'] },
  { emoji: '🔜', keywords: ['soon', 'arrow'] },
  { emoji: '🔝', keywords: ['top', 'arrow'] },

  // Nature & Places
  { emoji: '🌸', keywords: ['cherry', 'blossom', 'flower', 'spring'] },
  { emoji: '💮', keywords: ['flower', 'white'] },
  { emoji: '🏵️', keywords: ['rosette', 'flower'] },
  { emoji: '🌹', keywords: ['rose', 'flower', 'love'] },
  { emoji: '🥀', keywords: ['wilted', 'flower', 'dead'] },
  { emoji: '🌺', keywords: ['hibiscus', 'flower'] },
  { emoji: '🌻', keywords: ['sunflower', 'flower'] },
  { emoji: '🌼', keywords: ['blossom', 'flower'] },
  { emoji: '🌷', keywords: ['tulip', 'flower'] },
  { emoji: '🌱', keywords: ['seedling', 'plant', 'grow'] },
  { emoji: '🪴', keywords: ['plant', 'potted'] },
  { emoji: '🌲', keywords: ['tree', 'evergreen', 'christmas'] },
  { emoji: '🌳', keywords: ['tree', 'deciduous'] },
  { emoji: '🌴', keywords: ['palm', 'tree', 'tropical'] },
  { emoji: '🌵', keywords: ['cactus', 'desert'] },
  { emoji: '🌾', keywords: ['rice', 'plant', 'grain'] },
  { emoji: '🌿', keywords: ['herb', 'plant', 'leaf'] },
  { emoji: '☘️', keywords: ['shamrock', 'clover', 'irish'] },
  { emoji: '🍀', keywords: ['clover', 'luck', 'four leaf'] },
  { emoji: '🍁', keywords: ['maple', 'leaf', 'fall', 'autumn'] },
  { emoji: '🍂', keywords: ['fallen', 'leaf', 'autumn'] },
  { emoji: '🍃', keywords: ['leaf', 'wind', 'blowing'] },
  { emoji: '🏠', keywords: ['house', 'home'] },
  { emoji: '🏡', keywords: ['house', 'garden', 'home'] },
  { emoji: '🏢', keywords: ['office', 'building'] },
  { emoji: '🏫', keywords: ['school', 'building'] },
  { emoji: '🏥', keywords: ['hospital', 'building'] },
  { emoji: '🏪', keywords: ['store', 'convenience', 'shop'] },
  { emoji: '⛪', keywords: ['church', 'building'] },
  { emoji: '🕌', keywords: ['mosque', 'building'] },
  { emoji: '🛕', keywords: ['temple', 'hindu', 'building'] },
  { emoji: '🕍', keywords: ['synagogue', 'building'] },
  { emoji: '⛩️', keywords: ['shrine', 'shinto', 'japan'] },
  { emoji: '🗼', keywords: ['tower', 'tokyo'] },
  { emoji: '🗽', keywords: ['statue', 'liberty', 'nyc'] },
  { emoji: '🏰', keywords: ['castle', 'european'] },
  { emoji: '🏯', keywords: ['castle', 'japanese'] },
  { emoji: '🏟️', keywords: ['stadium', 'sport'] },
  { emoji: '⛺', keywords: ['tent', 'camping'] },
  { emoji: '🏕️', keywords: ['camping', 'tent', 'outdoors'] },
  { emoji: '🏖️', keywords: ['beach', 'umbrella', 'vacation'] },
  { emoji: '🏜️', keywords: ['desert'] },
  { emoji: '🏝️', keywords: ['island', 'desert', 'tropical'] },
  { emoji: '🏞️', keywords: ['park', 'national', 'nature'] },
  { emoji: '🌅', keywords: ['sunrise', 'morning'] },
  { emoji: '🌄', keywords: ['sunrise', 'mountains'] },
  { emoji: '🌇', keywords: ['sunset', 'city'] },
  { emoji: '🌆', keywords: ['cityscape', 'dusk'] },
  { emoji: '🌃', keywords: ['night', 'stars', 'city'] },
  { emoji: '🌉', keywords: ['bridge', 'night'] },
  { emoji: '🌌', keywords: ['milky way', 'galaxy', 'space'] },
  { emoji: '🌠', keywords: ['shooting', 'star', 'wish'] },

  // Transportation
  { emoji: '🚗', keywords: ['car', 'automobile', 'vehicle'] },
  { emoji: '🚕', keywords: ['taxi', 'car', 'cab'] },
  { emoji: '🚙', keywords: ['suv', 'car', 'vehicle'] },
  { emoji: '🚌', keywords: ['bus', 'vehicle'] },
  { emoji: '🚎', keywords: ['trolleybus', 'bus'] },
  { emoji: '🏎️', keywords: ['race', 'car', 'racing', 'fast'] },
  { emoji: '🚓', keywords: ['police', 'car'] },
  { emoji: '🚑', keywords: ['ambulance', 'emergency'] },
  { emoji: '🚒', keywords: ['fire', 'truck', 'engine'] },
  { emoji: '🚐', keywords: ['minibus', 'van'] },
  { emoji: '🛻', keywords: ['pickup', 'truck'] },
  { emoji: '🚚', keywords: ['truck', 'delivery'] },
  { emoji: '🚛', keywords: ['truck', 'semi'] },
  { emoji: '🚜', keywords: ['tractor', 'farm'] },
  { emoji: '🏍️', keywords: ['motorcycle', 'bike'] },
  { emoji: '🛵', keywords: ['scooter', 'vespa'] },
  { emoji: '🚲', keywords: ['bicycle', 'bike'] },
  { emoji: '🛴', keywords: ['scooter', 'kick'] },
  { emoji: '✈️', keywords: ['airplane', 'plane', 'flight'] },
  { emoji: '🛫', keywords: ['departure', 'plane', 'takeoff'] },
  { emoji: '🛬', keywords: ['arrival', 'plane', 'landing'] },
  { emoji: '🚀', keywords: ['rocket', 'space', 'launch'] },
  { emoji: '🛸', keywords: ['ufo', 'alien', 'spaceship'] },
  { emoji: '🚁', keywords: ['helicopter'] },
  { emoji: '🛶', keywords: ['canoe', 'boat'] },
  { emoji: '⛵', keywords: ['sailboat', 'boat'] },
  { emoji: '🚤', keywords: ['speedboat', 'boat'] },
  { emoji: '🛥️', keywords: ['motorboat', 'boat'] },
  { emoji: '🚢', keywords: ['ship', 'boat', 'cruise'] },
  { emoji: '🚂', keywords: ['train', 'locomotive'] },
  { emoji: '🚃', keywords: ['train', 'railway'] },
  { emoji: '🚄', keywords: ['train', 'high speed', 'bullet'] },
  { emoji: '🚅', keywords: ['train', 'bullet', 'shinkansen'] },
  { emoji: '🚆', keywords: ['train'] },
  { emoji: '🚇', keywords: ['metro', 'subway'] },
  { emoji: '🚈', keywords: ['light rail', 'train'] },
  { emoji: '🚉', keywords: ['station', 'train'] },
];

export function searchEmojis(query: string): { emoji: string; keywords: string[] }[] {
  if (!query) return [];

  const lowerQuery = query.toLowerCase();

  return EMOJI_LIST.filter(item =>
    item.keywords.some(keyword => keyword.startsWith(lowerQuery))
  ).slice(0, 10);
}
